name: Register Flow
on:
  push:
    branches:
      - main
      - develop
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Pip update
      run: pip install -U wheel pip

    - name: Pip install requirements.txt
      run: pip install -r requirements.txt

    - name: Authenticate with Prefect Cloud
      run: prefect auth login -k $TOKEN
      env:
        TOKEN: "${{ github.ref == 'refs/heads/main' && secrets.PREFECT_AUTH || secrets.PREFECT_DEV_AUTH }}"

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - uses: int128/create-ecr-repository-action@v1
      id: ecr
      with:
        repository: prefect/customer-rfm-segmentation

    - name: Register flow
      run: prefect register -p flows/flow.py --project "test"