name: Register Flow from dev
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      TOKEN: fromJSON('[${{ secrets.PREFECT_DEV_AUTH }}, ${{ secrets.PREFECT_AUTH }}"]')[github.ref == 'refs/heads/main']

    steps:
    - uses: actions/checkout@v2

    - name: Pip update
      run: pip install -U wheel pip

    - name: Pip install requirements.txt
      run: pip install -r requirements.txt

    - name: Authenticate with Prefect Cloud
      run: prefect auth login -k $TOKEN

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: 'us-east-1'

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Register flow
      run: prefect register -p flows/flow.py --project "test"